<?php

return array (
  'version' => '5.4.3',
  'title' => 'Staff',
  'type' => 'staff',
  'id' => '60637a262b9d8',
  'updated' => 1617132928,
  'columns' => 
  array (
    '60637acb45a1cc' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '120',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '110',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637acb45a1cc',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Name',
      'width' => '275',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => 'title',
    ),
    '60637a6c5df3b8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Job title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5a8753261bc62',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637a6c5df3b8',
    ),
    '60637a598f5c28' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Email address',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5a8753401bc64',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637a598f5c28',
    ),
    '60637a852d0e58' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Phone number',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5a8753321bc63',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637a852d0e58',
    ),
    '60637a7ba5a1cc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'LinkedIn URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5a8753401bc64ab',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637a7ba5a1cc',
    ),
    'taxonomy-staffcategories' => 
    array (
      'type' => 'taxonomy-staffcategories',
      'label' => 'Staff Categories',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => 'taxonomy-staffcategories',
    ),
    '60637ac1256040' => 
    array (
      'type' => 'column-content',
      'label' => 'Content',
      'width' => '',
      'width_unit' => '%',
      'string_limit' => 'word_limit',
      'excerpt_length' => '5',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637ac1256040',
    ),
    '60637d7b476c8c' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '125',
      'width_unit' => 'px',
      'use_icon' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637d7b476c8c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);