<?php

return array (
  'version' => '5.6.4',
  'title' => 'Staff',
  'type' => 'staff',
  'id' => '60637a262b9d8',
  'updated' => 1647291661,
  'columns' => 
  array (
    '60637acb45a1cc' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '120',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '110',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637acb45a1cc',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Name',
      'width' => '275',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => 'title',
    ),
    'taxonomy-staffcategories' => 
    array (
      'type' => 'taxonomy-staffcategories',
      'label' => 'Staff Categories',
      'width' => '',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => 'taxonomy-staffcategories',
    ),
    '622fa513cc0830' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Job title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_622fa30cd7316',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fa513cc0830',
    ),
    '622fa5201ba5e4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Phone number',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_622fa31ad7317',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fa5201ba5e4',
    ),
    '622fa50b7020c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Email',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_622fa329d7318',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fa50b7020c4',
    ),
    '622fa52b2c0830' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'LinkedIn URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_622fa339d7319',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fa52b2c0830',
    ),
    '622fa53d5e3540' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Twitter URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_622fa359d731a',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fa53d5e3540',
    ),
    '622fa53497ced8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Facebook URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_622fa362d731b',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fa53497ced8',
    ),
    '60637ac1256040' => 
    array (
      'type' => 'column-content',
      'label' => 'Content',
      'width' => '',
      'width_unit' => '%',
      'string_limit' => 'word_limit',
      'excerpt_length' => '5',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'export' => 'off',
      'sort' => 'off',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637ac1256040',
    ),
    '622fad0441cac0' => 
    array (
      'type' => 'column-excerpt',
      'label' => 'Excerpt',
      'width' => '',
      'width_unit' => '%',
      'excerpt_length' => '5',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '622fad0441cac0',
    ),
    '60637d7b476c8c' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '125',
      'width_unit' => 'px',
      'use_icon' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60637d7b476c8c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);